Feat/remote file
ribbybibby/ssl_exporter pull request #144
Opened 2023-08-02 16:20 UTC by jaroug

Add support for probing a remote PEM file over http/https

This is a corner case to be able to monitor BIMI related certificates

- https://support.google.com/a/answer/10911320
- https://support.google.com/a/answer/10911321

2024-01-05 14:47 UTC, dragoangel commented
Looks nice

2024-01-05 14:54 UTC, ribbybibby requested changes
Thank you for this PR and sorry for taking so long to review it!

I have a few comments

1. I don't think this should export `ssl_file_cert_*` metrics. We should just read the certificates out of the response body and export the regular `ssl_cert_*` metrics. We don't need the intermediate step where we write them to disk.
2. This also exports metrics from the TLS connection because it reuses the tls config used in the https prober: https://github.com/ribbybibby/ssl_exporter/blob/42d1d4ff0f0b08e405457277eb83460d16c278d1/prober/tls.go#L30. I don't think it should do this. It should only export metrics for the certificates returned in the response body.
3. Can you please improve the tests so that they actually verify the exported metrics?

2024-01-07 16:09 UTC, jaroug commented
Hi :) no worries I'm glad the project is still alive.

I made the changes requested, at least I hope it matches your expectations. I honestly can't remember why I thought it was a good idea to download the file :sweat_smile:

2024-01-17 12:41 UTC, dragoangel commented
LGTM

2024-02-23 14:33 UTC, dragoangel commented
@ribbybibby can you please review if this PR now is okay?

2024-03-20 12:22 UTC, ribbybibby commented on prober/remote_file.go
> +// ProbeFile collects certificate metrics from local files
```suggestion
// ProbeFile collects certificate metrics from a remote file
```

2024-03-20 12:25 UTC, ribbybibby commented on prober/remote_file.go
> +		certs, err := decodeCertificates([]byte(body))
These errors should be handled.

2024-03-20 12:27 UTC, ribbybibby commented on README.md
> +specified remote target.
```suggestion
The `remote_file` prober exports `ssl_cert_not_after` and
`ssl_cert_not_before` for PEM encoded certificates found at the
specified remote target.
```

2024-03-21 13:04 UTC, ribbybibby requested changes
Changes suggested/requested in comments.

2024-04-28 15:47 UTC, ribbybibby commented
Thank you for the contribution @jaroug. I've made some of my suggested changes and fixed some other things up and now I think this is good to merge.

2024-04-28 15:48 UTC, merged

2024-04-29 08:24 UTC, dragoangel commented
@ribbybibby can we get 2.5.0 released with this feature please? 🙏

2024-06-06 16:39 UTC, dragoangel commented
@ribbybibby kind reminder - this feature not get into 2.4.3 release, as it was been released before merging this branch.

2024-08-22 13:33 UTC, dragoangel commented
@jaroug btw, I found out that `ssl_verified_cert_not_after` not available as metrics for `http_file`, is this desired behaviour?

2025-05-12 08:50 UTC, cHiv0rz commented
@ribbybibby do you have plans to create a new release including this functionality?

2025-05-12 08:52 UTC, dragoangel commented
@cHiv0rz I also was waiting for it, but ended up building own image and pushing it to my registry.

2025-05-12 09:42 UTC, cHiv0rz commented
Yes, mee to, compiling from master and uploading the image. But just wanted to know if the exporter will be maintained or not :D

2025-05-12 10:11 UTC, cHiv0rz commented
@dragoangel do you use this functionality for BIMI certificates? 

I'm getting the following error:

```sh
ts=2025-05-12T10:08:16.013Z caller=ssl_exporter.go:107 level=error target=https://some/target/file.pem prober=http_file timeout=15s msg="making http request: Get \"https://some/target/file.pem": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

There certificate was issued by DigiCert, that I think is known abroad 😓 Have you faced this problem?

2025-05-12 10:46 UTC, cHiv0rz commented
nevermind, it was my fault not adding the certificates to the scratch container

2025-05-12 12:36 UTC, dragoangel commented
Yep, using and it works good