[added] release target add loongarch64
ribbybibby/ssl_exporter pull request #70
Opened 2021-05-07 03:07 UTC by duchuanLX

[added] release target add loongarch64

loongarch64 is Loongson's latest instruction set, and the server market has a lot of users in China.

PTAL.thanks。
@ribbybibby

2021-06-08 15:42 UTC, xen0n requested changes
IIRC LoongArch support is not upstream in Go? Even the proposal golang/go#46229 hasn't been accepted yet, the exact GOARCH value hasn't been decided. Maybe we should wait a bit?

2021-06-09 06:44 UTC, duchuanLX commented
> IIRC LoongArch support is not upstream in Go? Even the proposal [golang/go#46229](https://github.com/golang/go/issues/46229) hasn't been accepted yet, the exact GOARCH value hasn't been decided. Maybe we should wait a bit?
> 
> Also the English in commit message is a bit broken, and doesn't adhere to project convention. Maybe something like "Add loongarch64 to release targets" would be better. (Of course, change the "loongarch64" part to whatever gets finally accepted as the GOARCH value to use.)

You are right. Currently, cross-compilation does not support loongarch64, and the field of goarch has not yet been determined. I will continue to follow up, thank you for your reminder.

2021-06-09 08:33 UTC, duchuanLX commented
goarch

2021-06-09 09:30 UTC, duchuanLX commented
Wait until the goarch field is confirmed and cross-compilation is supported, and then resubmit.

2021-06-09 09:30 UTC, closed without merging